services:
  - type: web
    name: compliance-api
    env: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CELERY_BROKER_URL
        sync: false

  - type: worker
    name: compliance-worker
    env: docker
    plan: free
    dockerCommand: celery -A app.worker.celery_app worker --loglevel=info
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CELERY_BROKER_URL
        sync: false