from pydantic import BaseModel, ConfigDict, Field
from typing import Optional

# 1. Base Schema
# Contains only the core attributes that perfectly mirror the SQLAlchemy model.
class ProductBase(BaseModel):
    name: str = Field(..., description="The commercial name of the product or component")
    model_number: str = Field(..., description="The unique manufacturer model number used for physical tracking")
    description: Optional[str] = Field(None, description="Detailed description of the component and its function")

# 2. Create Schema
# Used specifically for POST requests when logging a new manufactured component.
class ProductCreate(ProductBase):
    pass

# 3. Update Schema
# Used for PATCH requests. All fields are optional to allow partial updates 
# (e.g., if a component's description needs an update but the model number remains unchanged).
class ProductUpdate(BaseModel):
    name: Optional[str] = None
    model_number: Optional[str] = None
    description: Optional[str] = None

# 4. Response Schema
# Used to format the data sent back to the client, including the primary key generated by the database.
class ProductResponse(ProductBase):
    id: int
    
    # This tells Pydantic to read the data directly from the SQLAlchemy ORM model
    model_config = ConfigDict(from_attributes=True)